// @vitest-environment node
import {describe,it,expect,vi} from 'vitest';
import {submitConcept,pollConcept,normalizeConcept,conceptPrompt,type ConceptStore,type ConceptProvider} from './design-concepts';
const input={id:'abcdef12-abcd-abcd-abcd-abcdef123456',title:'Arc quilted jacket',direction:'A collarless cropped jacket with curved offset quilt channels, a clean concealed snap placket, rounded split hem, and inset pockets. Washed cotton in faded olive.',targetMonth:'2026-12'};
function setup(){
 const data=new Map<string,any>();
 const store:ConceptStore={read:async(id,stage)=>structuredClone(data.get(id+stage)||null),create:async(id,stage,value)=>{const k=id+stage;if(data.has(k))return false;data.set(k,structuredClone(value));return true},saveImage:async(id,image)=>({...image,url:'https://saved.public.blob.vercel-storage.com/'+id+'.png'})};
 const provider:ConceptProvider={submit:vi.fn(async()=> 'provider-12345678'),poll:vi.fn(async()=>({status:'done',image:{url:'https://fal.media/test.png',width:2048,height:3072}}))};
 return {store,provider,data};
}
describe('original concept jobs',()=>{
 it('reserves once across concurrent callers and survives a later polling instance',async()=>{const {store,provider}=setup();const results=await Promise.all([submitConcept(store,provider,input),submitConcept(store,provider,input)]);expect(provider.submit).toHaveBeenCalledTimes(1);expect(results.every(r=>r.id===input.id)).toBe(true);const done=await pollConcept(store,provider,input.id);expect(done?.status).toBe('done');expect(done?.image?.url).toContain('saved.public.blob');expect(done?.prompt).toContain(input.direction);await pollConcept(store,provider,input.id);expect(provider.poll).toHaveBeenCalledTimes(1)});
 it('refuses a changed brief under the same request ID',async()=>{const {store,provider}=setup();await submitConcept(store,provider,input);await expect(submitConcept(store,provider,{...input,title:'Changed'})).rejects.toMatchObject({status:409});expect(provider.submit).toHaveBeenCalledTimes(1)});
 it('keeps ambiguous submission uncertain and never spends again on retry',async()=>{const {store,provider}=setup();provider.submit=vi.fn(async()=>{throw Error('timeout')});expect((await submitConcept(store,provider,input)).status).toBe('uncertain');await submitConcept(store,provider,input);expect(provider.submit).toHaveBeenCalledTimes(1)});
 it('does not convert an observation failure into a failed job or new charge',async()=>{const {store,provider}=setup();await submitConcept(store,provider,input);provider.poll=vi.fn(async()=>{throw Error('network unavailable')});await expect(pollConcept(store,provider,input.id)).rejects.toThrow();expect((await submitConcept(store,provider,input)).status).toBe('running');expect(provider.submit).toHaveBeenCalledTimes(1)});
 it('retries saving a completed image without another render',async()=>{const {store,provider}=setup();await submitConcept(store,provider,input);const save=store.saveImage;store.saveImage=async()=>{throw Error('storage down')};await expect(pollConcept(store,provider,input.id)).rejects.toThrow();store.saveImage=save;expect((await pollConcept(store,provider,input.id))?.status).toBe('done');expect(provider.submit).toHaveBeenCalledTimes(1)});
 it('records explicit provider failure and returns unknown task as null',async()=>{const {store,provider}=setup();await submitConcept(store,provider,input);provider.poll=async()=>({status:'failed',error:'Provider rejected concept'});expect((await pollConcept(store,provider,input.id))?.status).toBe('failed');expect(await pollConcept(store,provider,'ffffffff-abcd-abcd-abcd-abcdef123456')).toBeNull()});
 it('does not spend if durable reservation fails',async()=>{const {store,provider}=setup();store.create=async()=>{throw Error('storage down')};await expect(submitConcept(store,provider,input)).rejects.toThrow();expect(provider.submit).not.toHaveBeenCalled()});
 it('validates inputs and uses a new-garment prompt without claimed technical measurements',()=>{expect(()=>normalizeConcept({...input,id:'../../../invalid'})).toThrow();expect(()=>normalizeConcept({...input,targetMonth:'2026-13'})).toThrow();expect(()=>normalizeConcept({...input,direction:'jacket'})).toThrow();const p=conceptPrompt(input);expect(p).toContain('original womenswear');expect(p).toContain('matching back flat');expect(p).toContain('No invented measurements')});
});
