// GENERATED by scripts/build-models-manifest.mts — do not edit by hand.
//
// next.config.js excludes public/models from the API functions' file tracing,
// so on Vercel the routes read this manifest instead of the filesystem. A plate
// that is on disk but missing here does not exist as far as the deployed API is
// concerned. Regenerate with: npm run models:manifest
import type { HumanModel } from "./models-registry";

export const STATIC_HUMAN_MODELS = [
  {
    "id": "crop 01",
    "name": "Crop 01",
    "poses": [
      {
        "id": "crop 01",
        "label": "Crop 01",
        "publicPath": "/models/crop 01/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 01/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 01/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 01/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 02",
    "name": "Crop 02",
    "poses": [
      {
        "id": "crop 02",
        "label": "Crop 02",
        "publicPath": "/models/crop 02/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 02/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 02/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 02/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 03",
    "name": "Crop 03",
    "poses": [
      {
        "id": "crop 03",
        "label": "Crop 03",
        "publicPath": "/models/crop 03/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 03/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 03/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 03/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 04",
    "name": "Crop 04",
    "poses": [
      {
        "id": "crop 04",
        "label": "Crop 04",
        "publicPath": "/models/crop 04/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 04/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 04/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 04/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 05",
    "name": "Crop 05",
    "poses": [
      {
        "id": "crop 05",
        "label": "Crop 05",
        "publicPath": "/models/crop 05/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 05/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 05/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 05/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 06",
    "name": "Crop 06",
    "poses": [
      {
        "id": "crop 06",
        "label": "Crop 06",
        "publicPath": "/models/crop 06/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 06/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 06/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 06/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 07",
    "name": "Crop 07",
    "poses": [
      {
        "id": "crop 07",
        "label": "Crop 07",
        "publicPath": "/models/crop 07/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 07/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 07/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 07/side.jpg"
          }
        }
      }
    ],
    "wears": "shorts",
    "lowOk": true
  },
  {
    "id": "crop 08",
    "name": "Crop 08",
    "poses": [
      {
        "id": "crop 08",
        "label": "Crop 08",
        "publicPath": "/models/crop 08/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 08/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 08/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 08/side.jpg"
          }
        }
      }
    ],
    "wears": "skirt",
    "lowOk": false
  },
  {
    "id": "crop 09",
    "name": "Crop 09",
    "poses": [
      {
        "id": "crop 09",
        "label": "Crop 09",
        "publicPath": "/models/crop 09/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 09/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 09/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 09/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 10",
    "name": "Crop 10",
    "poses": [
      {
        "id": "crop 10",
        "label": "Crop 10",
        "publicPath": "/models/crop 10/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 10/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 10/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 10/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 11",
    "name": "Crop 11",
    "poses": [
      {
        "id": "crop 11",
        "label": "Crop 11",
        "publicPath": "/models/crop 11/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 11/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 11/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 11/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 12",
    "name": "Crop 12",
    "poses": [
      {
        "id": "crop 12",
        "label": "Crop 12",
        "publicPath": "/models/crop 12/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 12/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 12/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 12/side.jpg"
          }
        }
      }
    ],
    "wears": "skirt",
    "lowOk": false
  },
  {
    "id": "crop 13",
    "name": "Crop 13",
    "poses": [
      {
        "id": "crop 13",
        "label": "Crop 13",
        "publicPath": "/models/crop 13/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 13/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 13/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 13/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 14",
    "name": "Crop 14",
    "poses": [
      {
        "id": "crop 14",
        "label": "Crop 14",
        "publicPath": "/models/crop 14/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 14/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 14/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 14/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 15",
    "name": "Crop 15",
    "poses": [
      {
        "id": "crop 15",
        "label": "Crop 15",
        "publicPath": "/models/crop 15/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 15/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 15/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 15/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 16",
    "name": "Crop 16",
    "poses": [
      {
        "id": "crop 16",
        "label": "Crop 16",
        "publicPath": "/models/crop 16/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 16/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 16/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 16/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 17",
    "name": "Crop 17",
    "poses": [
      {
        "id": "crop 17",
        "label": "Crop 17",
        "publicPath": "/models/crop 17/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 17/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 17/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 17/side.jpg"
          }
        }
      }
    ],
    "wears": "shorts",
    "lowOk": true
  },
  {
    "id": "crop 18",
    "name": "Crop 18",
    "poses": [
      {
        "id": "crop 18",
        "label": "Crop 18",
        "publicPath": "/models/crop 18/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 18/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 18/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 18/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 19",
    "name": "Crop 19",
    "poses": [
      {
        "id": "crop 19",
        "label": "Crop 19",
        "publicPath": "/models/crop 19/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 19/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 19/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 19/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 20",
    "name": "Crop 20",
    "poses": [
      {
        "id": "crop 20",
        "label": "Crop 20",
        "publicPath": "/models/crop 20/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 20/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 20/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 20/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 21",
    "name": "Crop 21",
    "poses": [
      {
        "id": "crop 21",
        "label": "Crop 21",
        "publicPath": "/models/crop 21/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 21/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 21/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 21/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "silhouette": "barrel"
  },
  {
    "id": "crop 22",
    "name": "Crop 22",
    "poses": [
      {
        "id": "crop 22",
        "label": "Crop 22",
        "publicPath": "/models/crop 22/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 22/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 22/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 22/side.jpg"
          }
        }
      }
    ],
    "wears": "skirt",
    "lowOk": false
  },
  {
    "id": "crop 23",
    "name": "Crop 23",
    "poses": [
      {
        "id": "crop 23",
        "label": "Crop 23",
        "publicPath": "/models/crop 23/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 23/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 23/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 23/side.jpg"
          }
        }
      }
    ],
    "wears": "skirt",
    "lowOk": false
  },
  {
    "id": "crop 24",
    "name": "Crop 24",
    "poses": [
      {
        "id": "crop 24",
        "label": "Crop 24",
        "publicPath": "/models/crop 24/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 24/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 24/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 24/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 25",
    "name": "Crop 25",
    "poses": [
      {
        "id": "crop 25",
        "label": "Crop 25",
        "publicPath": "/models/crop 25/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 25/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 25/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 25/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 26",
    "name": "Crop 26",
    "poses": [
      {
        "id": "crop 26",
        "label": "Crop 26",
        "publicPath": "/models/crop 26/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 26/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 26/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 26/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 27",
    "name": "Crop 27",
    "poses": [
      {
        "id": "crop 27",
        "label": "Crop 27",
        "publicPath": "/models/crop 27/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 27/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 27/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 27/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 28",
    "name": "Crop 28",
    "poses": [
      {
        "id": "crop 28",
        "label": "Crop 28",
        "publicPath": "/models/crop 28/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 28/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 28/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 28/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 29",
    "name": "Crop 29",
    "poses": [
      {
        "id": "crop 29",
        "label": "Crop 29",
        "publicPath": "/models/crop 29/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 29/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 29/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 29/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 30",
    "name": "Crop 30",
    "poses": [
      {
        "id": "crop 30",
        "label": "Crop 30",
        "publicPath": "/models/crop 30/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 30/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 30/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 30/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 31",
    "name": "Crop 31",
    "poses": [
      {
        "id": "crop 31",
        "label": "Crop 31",
        "publicPath": "/models/crop 31/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 31/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 31/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 31/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 32",
    "name": "Crop 32",
    "poses": [
      {
        "id": "crop 32",
        "label": "Crop 32",
        "publicPath": "/models/crop 32/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 32/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 32/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 32/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 33",
    "name": "Crop 33",
    "poses": [
      {
        "id": "crop 33",
        "label": "Crop 33",
        "publicPath": "/models/crop 33/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 33/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 33/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 33/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 34",
    "name": "Crop 34",
    "poses": [
      {
        "id": "crop 34",
        "label": "Crop 34",
        "publicPath": "/models/crop 34/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 34/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 34/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 34/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 35",
    "name": "Crop 35",
    "poses": [
      {
        "id": "crop 35",
        "label": "Crop 35",
        "publicPath": "/models/crop 35/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 35/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 35/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 35/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 36",
    "name": "Crop 36",
    "poses": [
      {
        "id": "crop 36",
        "label": "Crop 36",
        "publicPath": "/models/crop 36/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 36/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 36/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 36/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "crop 37",
    "name": "Crop 37",
    "poses": [
      {
        "id": "crop 37",
        "label": "Crop 37",
        "publicPath": "/models/crop 37/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 37/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 37/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 37/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "faces",
    "name": "Faces",
    "poses": [
      {
        "id": "vision face",
        "label": "Vision Face",
        "publicPath": "/models/faces/vision-face.png",
        "filename": "vision-face.png",
        "subdir": "",
        "views": {
          "front": {
            "filename": "vision-face.png",
            "publicPath": "/models/faces/vision-face.png"
          }
        }
      },
      {
        "id": "vision smile face",
        "label": "Vision Smile Face",
        "publicPath": "/models/faces/vision-smile-face.png",
        "filename": "vision-smile-face.png",
        "subdir": "",
        "views": {
          "front": {
            "filename": "vision-smile-face.png",
            "publicPath": "/models/faces/vision-smile-face.png"
          }
        }
      }
    ]
  },
  {
    "id": "low 01",
    "name": "Low 01",
    "poses": [
      {
        "id": "low 01",
        "label": "Low 01",
        "publicPath": "/models/low 01/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 01/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 01/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 02",
    "name": "Low 02",
    "poses": [
      {
        "id": "low 02",
        "label": "Low 02",
        "publicPath": "/models/low 02/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 02/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 02/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 03",
    "name": "Low 03",
    "poses": [
      {
        "id": "low 03",
        "label": "Low 03",
        "publicPath": "/models/low 03/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 03/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 03/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 04",
    "name": "Low 04",
    "poses": [
      {
        "id": "low 04",
        "label": "Low 04",
        "publicPath": "/models/low 04/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 04/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 04/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 05",
    "name": "Low 05",
    "poses": [
      {
        "id": "low 05",
        "label": "Low 05",
        "publicPath": "/models/low 05/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 05/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 05/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 06",
    "name": "Low 06",
    "poses": [
      {
        "id": "low 06",
        "label": "Low 06",
        "publicPath": "/models/low 06/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 06/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 06/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 07",
    "name": "Low 07",
    "poses": [
      {
        "id": "low 07",
        "label": "Low 07",
        "publicPath": "/models/low 07/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 07/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 07/side.jpg"
          }
        }
      }
    ],
    "wears": "shorts",
    "lowOk": true
  },
  {
    "id": "low 08",
    "name": "Low 08",
    "poses": [
      {
        "id": "low 08",
        "label": "Low 08",
        "publicPath": "/models/low 08/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 08/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 08/side.jpg"
          }
        }
      }
    ],
    "wears": "skirt",
    "lowOk": false
  },
  {
    "id": "low 09",
    "name": "Low 09",
    "poses": [
      {
        "id": "low 09",
        "label": "Low 09",
        "publicPath": "/models/low 09/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 09/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 09/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 10",
    "name": "Low 10",
    "poses": [
      {
        "id": "low 10",
        "label": "Low 10",
        "publicPath": "/models/low 10/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 10/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 10/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 11",
    "name": "Low 11",
    "poses": [
      {
        "id": "low 11",
        "label": "Low 11",
        "publicPath": "/models/low 11/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 11/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 11/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 12",
    "name": "Low 12",
    "poses": [
      {
        "id": "low 12",
        "label": "Low 12",
        "publicPath": "/models/low 12/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 12/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 12/side.jpg"
          }
        }
      }
    ],
    "wears": "skirt",
    "lowOk": false
  },
  {
    "id": "low 13",
    "name": "Low 13",
    "poses": [
      {
        "id": "low 13",
        "label": "Low 13",
        "publicPath": "/models/low 13/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 13/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 13/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 14",
    "name": "Low 14",
    "poses": [
      {
        "id": "low 14",
        "label": "Low 14",
        "publicPath": "/models/low 14/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 14/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 14/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 15",
    "name": "Low 15",
    "poses": [
      {
        "id": "low 15",
        "label": "Low 15",
        "publicPath": "/models/low 15/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 15/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 15/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 16",
    "name": "Low 16",
    "poses": [
      {
        "id": "low 16",
        "label": "Low 16",
        "publicPath": "/models/low 16/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 16/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 16/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 17",
    "name": "Low 17",
    "poses": [
      {
        "id": "low 17",
        "label": "Low 17",
        "publicPath": "/models/low 17/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 17/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 17/side.jpg"
          }
        }
      }
    ],
    "wears": "shorts",
    "lowOk": true
  },
  {
    "id": "low 18",
    "name": "Low 18",
    "poses": [
      {
        "id": "low 18",
        "label": "Low 18",
        "publicPath": "/models/low 18/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 18/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 18/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 19",
    "name": "Low 19",
    "poses": [
      {
        "id": "low 19",
        "label": "Low 19",
        "publicPath": "/models/low 19/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 19/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 19/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 20",
    "name": "Low 20",
    "poses": [
      {
        "id": "low 20",
        "label": "Low 20",
        "publicPath": "/models/low 20/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 20/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 20/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 21",
    "name": "Low 21",
    "poses": [
      {
        "id": "low 21",
        "label": "Low 21",
        "publicPath": "/models/low 21/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 21/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 21/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "silhouette": "barrel"
  },
  {
    "id": "low 22",
    "name": "Low 22",
    "poses": [
      {
        "id": "low 22",
        "label": "Low 22",
        "publicPath": "/models/low 22/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 22/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 22/side.jpg"
          }
        }
      }
    ],
    "wears": "skirt",
    "lowOk": false
  },
  {
    "id": "low 23",
    "name": "Low 23",
    "poses": [
      {
        "id": "low 23",
        "label": "Low 23",
        "publicPath": "/models/low 23/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 23/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 23/side.jpg"
          }
        }
      }
    ],
    "wears": "skirt",
    "lowOk": false
  },
  {
    "id": "low 24",
    "name": "Low 24",
    "poses": [
      {
        "id": "low 24",
        "label": "Low 24",
        "publicPath": "/models/low 24/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 24/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 24/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 25",
    "name": "Low 25",
    "poses": [
      {
        "id": "low 25",
        "label": "Low 25",
        "publicPath": "/models/low 25/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 25/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 25/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 26",
    "name": "Low 26",
    "poses": [
      {
        "id": "low 26",
        "label": "Low 26",
        "publicPath": "/models/low 26/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 26/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 26/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 27",
    "name": "Low 27",
    "poses": [
      {
        "id": "low 27",
        "label": "Low 27",
        "publicPath": "/models/low 27/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 27/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 27/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 28",
    "name": "Low 28",
    "poses": [
      {
        "id": "low 28",
        "label": "Low 28",
        "publicPath": "/models/low 28/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 28/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 28/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 29",
    "name": "Low 29",
    "poses": [
      {
        "id": "low 29",
        "label": "Low 29",
        "publicPath": "/models/low 29/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 29/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 29/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 30",
    "name": "Low 30",
    "poses": [
      {
        "id": "low 30",
        "label": "Low 30",
        "publicPath": "/models/low 30/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 30/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 30/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 31",
    "name": "Low 31",
    "poses": [
      {
        "id": "low 31",
        "label": "Low 31",
        "publicPath": "/models/low 31/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 31/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 31/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 32",
    "name": "Low 32",
    "poses": [
      {
        "id": "low 32",
        "label": "Low 32",
        "publicPath": "/models/low 32/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 32/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 32/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 33",
    "name": "Low 33",
    "poses": [
      {
        "id": "low 33",
        "label": "Low 33",
        "publicPath": "/models/low 33/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 33/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 33/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 34",
    "name": "Low 34",
    "poses": [
      {
        "id": "low 34",
        "label": "Low 34",
        "publicPath": "/models/low 34/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 34/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 34/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 35",
    "name": "Low 35",
    "poses": [
      {
        "id": "low 35",
        "label": "Low 35",
        "publicPath": "/models/low 35/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 35/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 35/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 36",
    "name": "Low 36",
    "poses": [
      {
        "id": "low 36",
        "label": "Low 36",
        "publicPath": "/models/low 36/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 36/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 36/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "low 37",
    "name": "Low 37",
    "poses": [
      {
        "id": "low 37",
        "label": "Low 37",
        "publicPath": "/models/low 37/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 37/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 37/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 01",
    "name": "Studio 01",
    "poses": [
      {
        "id": "studio 01",
        "label": "Studio 01",
        "publicPath": "/models/studio 01/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 01/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 01/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 01/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 01/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 02",
    "name": "Studio 02",
    "poses": [
      {
        "id": "studio 02",
        "label": "Studio 02",
        "publicPath": "/models/studio 02/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 02/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 02/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 02/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 02/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 03",
    "name": "Studio 03",
    "poses": [
      {
        "id": "studio 03",
        "label": "Studio 03",
        "publicPath": "/models/studio 03/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 03/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 03/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 03/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 03/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 04",
    "name": "Studio 04",
    "poses": [
      {
        "id": "studio 04",
        "label": "Studio 04",
        "publicPath": "/models/studio 04/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 04/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 04/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 04/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 04/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 05",
    "name": "Studio 05",
    "poses": [
      {
        "id": "studio 05",
        "label": "Studio 05",
        "publicPath": "/models/studio 05/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 05/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 05/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 05/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 05/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 06",
    "name": "Studio 06",
    "poses": [
      {
        "id": "studio 06",
        "label": "Studio 06",
        "publicPath": "/models/studio 06/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 06/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 06/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 06/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 06/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 07",
    "name": "Studio 07",
    "poses": [
      {
        "id": "studio 07",
        "label": "Studio 07",
        "publicPath": "/models/studio 07/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 07/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 07/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 07/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 07/side.jpg"
          }
        }
      }
    ],
    "wears": "shorts",
    "lowOk": true
  },
  {
    "id": "studio 08",
    "name": "Studio 08",
    "poses": [
      {
        "id": "studio 08",
        "label": "Studio 08",
        "publicPath": "/models/studio 08/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 08/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 08/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 08/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 08/side.jpg"
          }
        }
      }
    ],
    "wears": "skirt",
    "lowOk": false
  },
  {
    "id": "studio 09",
    "name": "Studio 09",
    "poses": [
      {
        "id": "studio 09",
        "label": "Studio 09",
        "publicPath": "/models/studio 09/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 09/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 09/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 09/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 09/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 10",
    "name": "Studio 10",
    "poses": [
      {
        "id": "studio 10",
        "label": "Studio 10",
        "publicPath": "/models/studio 10/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 10/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 10/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 10/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 10/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 11",
    "name": "Studio 11",
    "poses": [
      {
        "id": "studio 11",
        "label": "Studio 11",
        "publicPath": "/models/studio 11/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 11/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 11/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 11/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 11/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 12",
    "name": "Studio 12",
    "poses": [
      {
        "id": "studio 12",
        "label": "Studio 12",
        "publicPath": "/models/studio 12/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 12/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 12/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 12/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 12/side.jpg"
          }
        }
      }
    ],
    "wears": "skirt",
    "lowOk": false
  },
  {
    "id": "studio 13",
    "name": "Studio 13",
    "poses": [
      {
        "id": "studio 13",
        "label": "Studio 13",
        "publicPath": "/models/studio 13/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 13/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 13/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 13/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 13/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 14",
    "name": "Studio 14",
    "poses": [
      {
        "id": "studio 14",
        "label": "Studio 14",
        "publicPath": "/models/studio 14/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 14/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 14/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 14/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 14/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 15",
    "name": "Studio 15",
    "poses": [
      {
        "id": "studio 15",
        "label": "Studio 15",
        "publicPath": "/models/studio 15/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 15/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 15/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 15/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 15/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 16",
    "name": "Studio 16",
    "poses": [
      {
        "id": "studio 16",
        "label": "Studio 16",
        "publicPath": "/models/studio 16/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 16/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 16/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 16/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 16/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 17",
    "name": "Studio 17",
    "poses": [
      {
        "id": "studio 17",
        "label": "Studio 17",
        "publicPath": "/models/studio 17/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 17/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 17/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 17/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 17/side.jpg"
          }
        }
      }
    ],
    "wears": "shorts",
    "lowOk": true
  },
  {
    "id": "studio 18",
    "name": "Studio 18",
    "poses": [
      {
        "id": "studio 18",
        "label": "Studio 18",
        "publicPath": "/models/studio 18/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 18/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 18/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 18/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 18/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 19",
    "name": "Studio 19",
    "poses": [
      {
        "id": "studio 19",
        "label": "Studio 19",
        "publicPath": "/models/studio 19/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 19/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 19/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 19/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 19/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 20",
    "name": "Studio 20",
    "poses": [
      {
        "id": "studio 20",
        "label": "Studio 20",
        "publicPath": "/models/studio 20/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 20/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 20/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 20/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 20/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 21",
    "name": "Studio 21",
    "poses": [
      {
        "id": "studio 21",
        "label": "Studio 21",
        "publicPath": "/models/studio 21/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 21/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 21/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 21/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 21/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "silhouette": "barrel"
  },
  {
    "id": "studio 22",
    "name": "Studio 22",
    "poses": [
      {
        "id": "studio 22",
        "label": "Studio 22",
        "publicPath": "/models/studio 22/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 22/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 22/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 22/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 22/side.jpg"
          }
        }
      }
    ],
    "wears": "skirt",
    "lowOk": false
  },
  {
    "id": "studio 23",
    "name": "Studio 23",
    "poses": [
      {
        "id": "studio 23",
        "label": "Studio 23",
        "publicPath": "/models/studio 23/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 23/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 23/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 23/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 23/side.jpg"
          }
        }
      }
    ],
    "wears": "skirt",
    "lowOk": false
  },
  {
    "id": "studio 24",
    "name": "Studio 24",
    "poses": [
      {
        "id": "studio 24",
        "label": "Studio 24",
        "publicPath": "/models/studio 24/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 24/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 24/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 24/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 24/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 25",
    "name": "Studio 25",
    "poses": [
      {
        "id": "studio 25",
        "label": "Studio 25",
        "publicPath": "/models/studio 25/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 25/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 25/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 25/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 25/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 26",
    "name": "Studio 26",
    "poses": [
      {
        "id": "studio 26",
        "label": "Studio 26",
        "publicPath": "/models/studio 26/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 26/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 26/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 26/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 26/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 27",
    "name": "Studio 27",
    "poses": [
      {
        "id": "studio 27",
        "label": "Studio 27",
        "publicPath": "/models/studio 27/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 27/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 27/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 27/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 27/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 28",
    "name": "Studio 28",
    "poses": [
      {
        "id": "studio 28",
        "label": "Studio 28",
        "publicPath": "/models/studio 28/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 28/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 28/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 28/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 28/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 29",
    "name": "Studio 29",
    "poses": [
      {
        "id": "studio 29",
        "label": "Studio 29",
        "publicPath": "/models/studio 29/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 29/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 29/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 29/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 29/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 30",
    "name": "Studio 30",
    "poses": [
      {
        "id": "studio 30",
        "label": "Studio 30",
        "publicPath": "/models/studio 30/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 30/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 30/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 30/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 30/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 31",
    "name": "Studio 31",
    "poses": [
      {
        "id": "studio 31",
        "label": "Studio 31",
        "publicPath": "/models/studio 31/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 31/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 31/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 31/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 31/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 32",
    "name": "Studio 32",
    "poses": [
      {
        "id": "studio 32",
        "label": "Studio 32",
        "publicPath": "/models/studio 32/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 32/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 32/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 32/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 32/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 33",
    "name": "Studio 33",
    "poses": [
      {
        "id": "studio 33",
        "label": "Studio 33",
        "publicPath": "/models/studio 33/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 33/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 33/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 33/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 33/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 34",
    "name": "Studio 34",
    "poses": [
      {
        "id": "studio 34",
        "label": "Studio 34",
        "publicPath": "/models/studio 34/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 34/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 34/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 34/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 34/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 35",
    "name": "Studio 35",
    "poses": [
      {
        "id": "studio 35",
        "label": "Studio 35",
        "publicPath": "/models/studio 35/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 35/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 35/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 35/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 35/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 36",
    "name": "Studio 36",
    "poses": [
      {
        "id": "studio 36",
        "label": "Studio 36",
        "publicPath": "/models/studio 36/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 36/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 36/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 36/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 36/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  },
  {
    "id": "studio 37",
    "name": "Studio 37",
    "poses": [
      {
        "id": "studio 37",
        "label": "Studio 37",
        "publicPath": "/models/studio 37/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 37/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 37/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 37/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 37/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true
  }
] as unknown as HumanModel[];
