// GENERATED by scripts/build-models-manifest.mts — do not edit by hand.
//
// next.config.js excludes public/models from the API functions' file tracing,
// so on Vercel the routes read this manifest instead of the filesystem. A plate
// that is on disk but missing here does not exist as far as the deployed API is
// concerned. Regenerate with: npm run models:manifest
import type { HumanModel } from "./models-registry";

export const STATIC_HUMAN_MODELS = [
  {
    "id": "crop 97",
    "name": "Vision",
    "poses": [
      {
        "id": "crop 97",
        "label": "Crop 97",
        "publicPath": "/models/crop 97/front.png",
        "filename": "front.png",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.png",
            "publicPath": "/models/crop 97/back.png"
          },
          "front": {
            "filename": "front.png",
            "publicPath": "/models/crop 97/front.png"
          },
          "side": {
            "filename": "side.png",
            "publicPath": "/models/crop 97/side.png"
          }
        }
      }
    ],
    "wears": "shorts",
    "lowOk": true,
    "pose": "Vision",
    "character": "vision",
    "expression": "neutral",
    "slug": "detp58027-vision-neutral",
    "poseKey": "detp58027-vision",
    "outfitAbove": "original pink and yellow striped tee",
    "outfitBelow": "original matching striped shorts",
    "autoPool": true
  },
  {
    "id": "crop 98",
    "name": "Celine",
    "poses": [
      {
        "id": "crop 98",
        "label": "Crop 98",
        "publicPath": "/models/crop 98/front.png",
        "filename": "front.png",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.png",
            "publicPath": "/models/crop 98/back.png"
          },
          "front": {
            "filename": "front.png",
            "publicPath": "/models/crop 98/front.png"
          },
          "side": {
            "filename": "side.png",
            "publicPath": "/models/crop 98/side.png"
          }
        }
      }
    ],
    "wears": "shorts",
    "lowOk": true,
    "pose": "Celine",
    "character": "celine",
    "expression": "neutral",
    "slug": "detp58027-celine-neutral",
    "poseKey": "detp58027-celine",
    "outfitAbove": "original pink and yellow striped tee",
    "outfitBelow": "original matching striped shorts",
    "autoPool": true
  },
  {
    "id": "low 97",
    "name": "Vision",
    "poses": [
      {
        "id": "low 97",
        "label": "Low 97",
        "publicPath": "/models/low 97/front.png",
        "filename": "front.png",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.png",
            "publicPath": "/models/low 97/front.png"
          },
          "side": {
            "filename": "side.png",
            "publicPath": "/models/low 97/side.png"
          }
        }
      }
    ],
    "wears": "shorts",
    "lowOk": true,
    "pose": "Vision",
    "character": "vision",
    "expression": "neutral",
    "slug": "detp58027-vision-neutral",
    "poseKey": "detp58027-vision",
    "outfitAbove": "original pink and yellow striped tee",
    "outfitBelow": "original matching striped shorts",
    "autoPool": true
  },
  {
    "id": "low 98",
    "name": "Celine",
    "poses": [
      {
        "id": "low 98",
        "label": "Low 98",
        "publicPath": "/models/low 98/front.png",
        "filename": "front.png",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.png",
            "publicPath": "/models/low 98/front.png"
          },
          "side": {
            "filename": "side.png",
            "publicPath": "/models/low 98/side.png"
          }
        }
      }
    ],
    "wears": "shorts",
    "lowOk": true,
    "pose": "Celine",
    "character": "celine",
    "expression": "neutral",
    "slug": "detp58027-celine-neutral",
    "poseKey": "detp58027-celine",
    "outfitAbove": "original pink and yellow striped tee",
    "outfitBelow": "original matching striped shorts",
    "autoPool": true
  },
  {
    "id": "studio 97",
    "name": "Vision",
    "poses": [
      {
        "id": "studio 97",
        "label": "Studio 97",
        "publicPath": "/models/studio 97/front.png",
        "filename": "front.png",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.png",
            "publicPath": "/models/studio 97/back.png"
          },
          "front": {
            "filename": "front.png",
            "publicPath": "/models/studio 97/front.png"
          },
          "full": {
            "filename": "full.png",
            "publicPath": "/models/studio 97/full.png"
          },
          "side": {
            "filename": "side.png",
            "publicPath": "/models/studio 97/side.png"
          }
        }
      }
    ],
    "wears": "shorts",
    "lowOk": true,
    "pose": "Vision",
    "character": "vision",
    "expression": "neutral",
    "slug": "detp58027-vision-neutral",
    "poseKey": "detp58027-vision",
    "outfitAbove": "original pink and yellow striped tee",
    "outfitBelow": "original matching striped shorts",
    "autoPool": true
  },
  {
    "id": "studio 98",
    "name": "Celine",
    "poses": [
      {
        "id": "studio 98",
        "label": "Studio 98",
        "publicPath": "/models/studio 98/front.png",
        "filename": "front.png",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.png",
            "publicPath": "/models/studio 98/back.png"
          },
          "front": {
            "filename": "front.png",
            "publicPath": "/models/studio 98/front.png"
          },
          "full": {
            "filename": "full.png",
            "publicPath": "/models/studio 98/full.png"
          },
          "side": {
            "filename": "side.png",
            "publicPath": "/models/studio 98/side.png"
          }
        }
      }
    ],
    "wears": "shorts",
    "lowOk": true,
    "pose": "Celine",
    "character": "celine",
    "expression": "neutral",
    "slug": "detp58027-celine-neutral",
    "poseKey": "detp58027-celine",
    "outfitAbove": "original pink and yellow striped tee",
    "outfitBelow": "original matching striped shorts",
    "autoPool": true
  }
] as unknown as HumanModel[];
