// GENERATED by scripts/build-models-manifest.mts — do not edit by hand.
//
// next.config.js excludes public/models from the API functions' file tracing,
// so on Vercel the routes read this manifest instead of the filesystem. A plate
// that is on disk but missing here does not exist as far as the deployed API is
// concerned. Regenerate with: npm run models:manifest
import type { HumanModel } from "./models-registry";

export const STATIC_HUMAN_MODELS = [
  {
    "id": "crop 03",
    "name": "Crop 03",
    "poses": [
      {
        "id": "crop 03",
        "label": "Crop 03",
        "publicPath": "/models/crop 03/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 03/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 03/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 03/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides, feet apart",
    "outfitAbove": "beige textured hooded button-up",
    "outfitBelow": "cream wide-leg trousers",
    "autoPool": true
  },
  {
    "id": "crop 04",
    "name": "Crop 04",
    "poses": [
      {
        "id": "crop 04",
        "label": "Crop 04",
        "publicPath": "/models/crop 04/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 04/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 04/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 04/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides, feet apart",
    "outfitAbove": "leopard print bomber jacket",
    "outfitBelow": "heather grey wide-leg sweatpants",
    "autoPool": true
  },
  {
    "id": "crop 05",
    "name": "Crop 05",
    "poses": [
      {
        "id": "crop 05",
        "label": "Crop 05",
        "publicPath": "/models/crop 05/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 05/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 05/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 05/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, both thumbs hooked in front pockets",
    "outfitAbove": "ivory ribbed turtleneck sweater",
    "outfitBelow": "brown plaid barrel trousers",
    "autoPool": true
  },
  {
    "id": "crop 06",
    "name": "Crop 06",
    "poses": [
      {
        "id": "crop 06",
        "label": "Crop 06",
        "publicPath": "/models/crop 06/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 06/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 06/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 06/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, one hand in pocket",
    "outfitAbove": "distressed cable-knit sweater",
    "outfitBelow": "acid-wash wide-leg jeans",
    "autoPool": true
  },
  {
    "id": "crop 07",
    "name": "Crop 07",
    "poses": [
      {
        "id": "crop 07",
        "label": "Crop 07",
        "publicPath": "/models/crop 07/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 07/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 07/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 07/side.jpg"
          }
        }
      }
    ],
    "wears": "shorts",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides, feet apart",
    "outfitAbove": "striped square-neck tank top",
    "outfitBelow": "multicolor striped linen shorts",
    "autoPool": true
  },
  {
    "id": "crop 09",
    "name": "Crop 09",
    "poses": [
      {
        "id": "crop 09",
        "label": "Crop 09",
        "publicPath": "/models/crop 09/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 09/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 09/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 09/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing upright, hands in pockets, feet slightly apart",
    "outfitAbove": "black unicorn-print cardigan",
    "outfitBelow": "polka-dot wide-leg trousers",
    "autoPool": true
  },
  {
    "id": "crop 10",
    "name": "Crop 10",
    "poses": [
      {
        "id": "crop 10",
        "label": "Crop 10",
        "publicPath": "/models/crop 10/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 10/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 10/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 10/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "outfitAbove": "taupe turtleneck sweater",
    "outfitBelow": "patchwork wide-leg jeans",
    "autoPool": true
  },
  {
    "id": "crop 19",
    "name": "Crop 19",
    "poses": [
      {
        "id": "crop 19",
        "label": "Crop 19",
        "publicPath": "/models/crop 19/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 19/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 19/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 19/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, right hand on hip, feet apart",
    "outfitAbove": "grey layered henley tank",
    "outfitBelow": "olive balloon barrel pants",
    "autoPool": true
  },
  {
    "id": "crop 20",
    "name": "Crop 20",
    "poses": [
      {
        "id": "crop 20",
        "label": "Crop 20",
        "publicPath": "/models/crop 20/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 20/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 20/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 20/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, arms relaxed",
    "outfitAbove": "black crewneck sweater layered tee",
    "outfitBelow": "charcoal pleated wide-leg trousers",
    "autoPool": true
  },
  {
    "id": "crop 22",
    "name": "Crop 22",
    "poses": [
      {
        "id": "crop 22",
        "label": "Crop 22",
        "publicPath": "/models/crop 22/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 22/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 22/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 22/side.jpg"
          }
        }
      }
    ],
    "wears": "skirt",
    "lowOk": false,
    "pose": "standing upright, arms at sides, feet slightly apart",
    "outfitAbove": "black sleeveless turtleneck top",
    "outfitBelow": "leopard print lace-hem midi skirt",
    "autoPool": true
  },
  {
    "id": "crop 25",
    "name": "Crop 25",
    "poses": [
      {
        "id": "crop 25",
        "label": "Crop 25",
        "publicPath": "/models/crop 25/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 25/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 25/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 25/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "Standing straight, one hand in pocket, feet apart",
    "outfitAbove": "taupe graphic tee",
    "outfitBelow": "brown polka-dot barrel pants",
    "autoPool": true
  },
  {
    "id": "crop 28",
    "name": "Crop 28",
    "poses": [
      {
        "id": "crop 28",
        "label": "Crop 28",
        "publicPath": "/models/crop 28/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 28/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 28/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 28/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "vision",
    "expression": "neutral",
    "slug": "dwt62133-24-neutral",
    "poseKey": "dwt62133-24",
    "outfitAbove": "red ruffle-collar cardigan",
    "outfitBelow": "patchwork wide-leg chambray pants",
    "autoPool": true
  },
  {
    "id": "crop 29",
    "name": "Crop 29",
    "poses": [
      {
        "id": "crop 29",
        "label": "Crop 29",
        "publicPath": "/models/crop 29/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 29/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 29/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 29/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "vision",
    "expression": "smile",
    "slug": "dwt62133-24-smile",
    "poseKey": "dwt62133-24",
    "outfitAbove": "red ruffle-collar cardigan",
    "outfitBelow": "patchwork wide-leg chambray pants",
    "autoPool": true
  },
  {
    "id": "crop 30",
    "name": "Crop 30",
    "poses": [
      {
        "id": "crop 30",
        "label": "Crop 30",
        "publicPath": "/models/crop 30/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 30/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 30/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 30/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "vision",
    "expression": "smirk",
    "slug": "dwt62133-24-smirk",
    "poseKey": "dwt62133-24",
    "outfitAbove": "red ruffle-collar cardigan",
    "outfitBelow": "patchwork wide-leg chambray pants",
    "autoPool": true
  },
  {
    "id": "crop 31",
    "name": "Crop 31",
    "poses": [
      {
        "id": "crop 31",
        "label": "Crop 31",
        "publicPath": "/models/crop 31/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 31/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 31/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 31/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "vision",
    "expression": "teeth",
    "slug": "dwt62133-24-teeth",
    "poseKey": "dwt62133-24",
    "outfitAbove": "red ruffle-collar cardigan",
    "outfitBelow": "patchwork wide-leg chambray pants",
    "autoPool": true
  },
  {
    "id": "crop 32",
    "name": "Crop 32",
    "poses": [
      {
        "id": "crop 32",
        "label": "Crop 32",
        "publicPath": "/models/crop 32/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 32/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 32/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 32/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, one arm raised to head, hand in pocket",
    "character": "vision",
    "expression": "neutral",
    "slug": "dwt62170-20-neutral",
    "poseKey": "dwt62170-20",
    "outfitAbove": "tan rodeo graphic sweater",
    "outfitBelow": "polka-dot barrel jeans",
    "autoPool": true
  },
  {
    "id": "crop 33",
    "name": "Crop 33",
    "poses": [
      {
        "id": "crop 33",
        "label": "Crop 33",
        "publicPath": "/models/crop 33/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 33/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 33/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 33/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, one arm raised to head, hand in pocket",
    "character": "vision",
    "expression": "smile",
    "slug": "dwt62170-20-smile",
    "poseKey": "dwt62170-20",
    "outfitAbove": "tan rodeo graphic sweater",
    "outfitBelow": "polka-dot barrel jeans",
    "autoPool": true
  },
  {
    "id": "crop 34",
    "name": "Crop 34",
    "poses": [
      {
        "id": "crop 34",
        "label": "Crop 34",
        "publicPath": "/models/crop 34/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 34/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 34/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 34/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, one arm raised to head, hand in pocket",
    "character": "vision",
    "expression": "teeth",
    "slug": "dwt62170-20-teeth",
    "poseKey": "dwt62170-20",
    "outfitAbove": "tan rodeo graphic sweater",
    "outfitBelow": "polka-dot barrel jeans",
    "autoPool": true
  },
  {
    "id": "crop 35",
    "name": "Crop 35",
    "poses": [
      {
        "id": "crop 35",
        "label": "Crop 35",
        "publicPath": "/models/crop 35/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 35/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 35/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 35/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, hand in pocket",
    "character": "vision",
    "expression": "neutral",
    "slug": "dwt62170-21-neutral",
    "poseKey": "dwt62170-21",
    "outfitAbove": "tan rodeo graphic sweater",
    "outfitBelow": "polka-dot barrel jeans",
    "autoPool": true
  },
  {
    "id": "crop 36",
    "name": "Crop 36",
    "poses": [
      {
        "id": "crop 36",
        "label": "Crop 36",
        "publicPath": "/models/crop 36/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 36/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 36/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 36/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, hand in pocket",
    "character": "vision",
    "expression": "smile",
    "slug": "dwt62170-21-smile",
    "poseKey": "dwt62170-21",
    "outfitAbove": "tan rodeo graphic sweater",
    "outfitBelow": "polka-dot barrel jeans",
    "autoPool": true
  },
  {
    "id": "crop 37",
    "name": "Crop 37",
    "poses": [
      {
        "id": "crop 37",
        "label": "Crop 37",
        "publicPath": "/models/crop 37/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 37/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 37/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 37/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, hand in pocket",
    "character": "vision",
    "expression": "teeth",
    "slug": "dwt62170-21-teeth",
    "poseKey": "dwt62170-21",
    "outfitAbove": "tan rodeo graphic sweater",
    "outfitBelow": "polka-dot barrel jeans",
    "autoPool": true
  },
  {
    "id": "crop 53",
    "name": "Crop 53",
    "poses": [
      {
        "id": "crop 53",
        "label": "Crop 53",
        "publicPath": "/models/crop 53/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 53/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 53/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 53/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "celine",
    "expression": "neutral",
    "slug": "dwt62133-24-celine-neutral",
    "poseKey": "dwt62133-24-celine",
    "autoPool": true
  },
  {
    "id": "crop 54",
    "name": "Crop 54",
    "poses": [
      {
        "id": "crop 54",
        "label": "Crop 54",
        "publicPath": "/models/crop 54/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 54/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 54/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 54/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "celine",
    "expression": "smile",
    "slug": "dwt62133-24-celine-smile",
    "poseKey": "dwt62133-24-celine",
    "autoPool": true
  },
  {
    "id": "crop 55",
    "name": "Crop 55",
    "poses": [
      {
        "id": "crop 55",
        "label": "Crop 55",
        "publicPath": "/models/crop 55/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 55/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 55/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 55/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "celine",
    "expression": "smirk",
    "slug": "dwt62133-24-celine-smirk",
    "poseKey": "dwt62133-24-celine",
    "autoPool": true
  },
  {
    "id": "crop 56",
    "name": "Crop 56",
    "poses": [
      {
        "id": "crop 56",
        "label": "Crop 56",
        "publicPath": "/models/crop 56/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 56/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 56/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 56/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "celine",
    "expression": "teeth",
    "slug": "dwt62133-24-celine-teeth",
    "poseKey": "dwt62133-24-celine",
    "autoPool": true
  },
  {
    "id": "crop 57",
    "name": "Crop 57",
    "poses": [
      {
        "id": "crop 57",
        "label": "Crop 57",
        "publicPath": "/models/crop 57/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 57/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 57/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 57/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, hand in pocket",
    "character": "celine",
    "expression": "neutral",
    "slug": "dwt62170-21-celine-neutral",
    "poseKey": "dwt62170-21-celine",
    "autoPool": true
  },
  {
    "id": "crop 58",
    "name": "Crop 58",
    "poses": [
      {
        "id": "crop 58",
        "label": "Crop 58",
        "publicPath": "/models/crop 58/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 58/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 58/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 58/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, hand in pocket",
    "character": "celine",
    "expression": "smile",
    "slug": "dwt62170-21-celine-smile",
    "poseKey": "dwt62170-21-celine",
    "autoPool": true
  },
  {
    "id": "crop 59",
    "name": "Crop 59",
    "poses": [
      {
        "id": "crop 59",
        "label": "Crop 59",
        "publicPath": "/models/crop 59/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 59/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 59/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 59/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, hand in pocket",
    "character": "celine",
    "expression": "smirk",
    "slug": "dwt62170-21-celine-smirk",
    "poseKey": "dwt62170-21-celine",
    "autoPool": true
  },
  {
    "id": "crop 60",
    "name": "Crop 60",
    "poses": [
      {
        "id": "crop 60",
        "label": "Crop 60",
        "publicPath": "/models/crop 60/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/crop 60/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/crop 60/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/crop 60/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, hand in pocket",
    "character": "celine",
    "expression": "teeth",
    "slug": "dwt62170-21-celine-teeth",
    "poseKey": "dwt62170-21-celine",
    "autoPool": true
  },
  {
    "id": "low 03",
    "name": "Low 03",
    "poses": [
      {
        "id": "low 03",
        "label": "Low 03",
        "publicPath": "/models/low 03/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 03/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 03/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides, feet apart",
    "outfitAbove": "beige textured hooded button-up",
    "outfitBelow": "cream wide-leg trousers",
    "autoPool": true
  },
  {
    "id": "low 04",
    "name": "Low 04",
    "poses": [
      {
        "id": "low 04",
        "label": "Low 04",
        "publicPath": "/models/low 04/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 04/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 04/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides, feet apart",
    "outfitAbove": "leopard print bomber jacket",
    "outfitBelow": "heather grey wide-leg sweatpants",
    "autoPool": true
  },
  {
    "id": "low 05",
    "name": "Low 05",
    "poses": [
      {
        "id": "low 05",
        "label": "Low 05",
        "publicPath": "/models/low 05/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 05/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 05/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, both thumbs hooked in front pockets",
    "outfitAbove": "ivory ribbed turtleneck sweater",
    "outfitBelow": "brown plaid barrel trousers",
    "autoPool": true
  },
  {
    "id": "low 06",
    "name": "Low 06",
    "poses": [
      {
        "id": "low 06",
        "label": "Low 06",
        "publicPath": "/models/low 06/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 06/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 06/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, one hand in pocket",
    "outfitAbove": "distressed cable-knit sweater",
    "outfitBelow": "acid-wash wide-leg jeans",
    "autoPool": true
  },
  {
    "id": "low 07",
    "name": "Low 07",
    "poses": [
      {
        "id": "low 07",
        "label": "Low 07",
        "publicPath": "/models/low 07/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 07/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 07/side.jpg"
          }
        }
      }
    ],
    "wears": "shorts",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides, feet apart",
    "outfitAbove": "striped square-neck tank top",
    "outfitBelow": "multicolor striped linen shorts",
    "autoPool": true
  },
  {
    "id": "low 09",
    "name": "Low 09",
    "poses": [
      {
        "id": "low 09",
        "label": "Low 09",
        "publicPath": "/models/low 09/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 09/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 09/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing upright, hands in pockets, feet slightly apart",
    "outfitAbove": "black unicorn-print cardigan",
    "outfitBelow": "polka-dot wide-leg trousers",
    "autoPool": true
  },
  {
    "id": "low 10",
    "name": "Low 10",
    "poses": [
      {
        "id": "low 10",
        "label": "Low 10",
        "publicPath": "/models/low 10/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 10/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 10/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "outfitAbove": "taupe turtleneck sweater",
    "outfitBelow": "patchwork wide-leg jeans",
    "autoPool": true
  },
  {
    "id": "low 19",
    "name": "Low 19",
    "poses": [
      {
        "id": "low 19",
        "label": "Low 19",
        "publicPath": "/models/low 19/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 19/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 19/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, right hand on hip, feet apart",
    "outfitAbove": "grey layered henley tank",
    "outfitBelow": "olive balloon barrel pants",
    "autoPool": true
  },
  {
    "id": "low 20",
    "name": "Low 20",
    "poses": [
      {
        "id": "low 20",
        "label": "Low 20",
        "publicPath": "/models/low 20/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 20/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 20/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, arms relaxed",
    "outfitAbove": "black crewneck sweater layered tee",
    "outfitBelow": "charcoal pleated wide-leg trousers",
    "autoPool": true
  },
  {
    "id": "low 22",
    "name": "Low 22",
    "poses": [
      {
        "id": "low 22",
        "label": "Low 22",
        "publicPath": "/models/low 22/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 22/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 22/side.jpg"
          }
        }
      }
    ],
    "wears": "skirt",
    "lowOk": false,
    "pose": "standing upright, arms at sides, feet slightly apart",
    "outfitAbove": "black sleeveless turtleneck top",
    "outfitBelow": "leopard print lace-hem midi skirt",
    "autoPool": true
  },
  {
    "id": "low 25",
    "name": "Low 25",
    "poses": [
      {
        "id": "low 25",
        "label": "Low 25",
        "publicPath": "/models/low 25/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 25/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 25/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "Standing straight, one hand in pocket, feet apart",
    "outfitAbove": "taupe graphic tee",
    "outfitBelow": "brown polka-dot barrel pants",
    "autoPool": true
  },
  {
    "id": "low 28",
    "name": "Low 28",
    "poses": [
      {
        "id": "low 28",
        "label": "Low 28",
        "publicPath": "/models/low 28/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 28/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 28/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "vision",
    "expression": "neutral",
    "slug": "dwt62133-24-neutral",
    "poseKey": "dwt62133-24",
    "outfitAbove": "red ruffle-collar cardigan",
    "outfitBelow": "patchwork wide-leg chambray pants",
    "autoPool": true
  },
  {
    "id": "low 29",
    "name": "Low 29",
    "poses": [
      {
        "id": "low 29",
        "label": "Low 29",
        "publicPath": "/models/low 29/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 29/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 29/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "vision",
    "expression": "smile",
    "slug": "dwt62133-24-smile",
    "poseKey": "dwt62133-24",
    "outfitAbove": "red ruffle-collar cardigan",
    "outfitBelow": "patchwork wide-leg chambray pants",
    "autoPool": true
  },
  {
    "id": "low 30",
    "name": "Low 30",
    "poses": [
      {
        "id": "low 30",
        "label": "Low 30",
        "publicPath": "/models/low 30/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 30/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 30/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "vision",
    "expression": "smirk",
    "slug": "dwt62133-24-smirk",
    "poseKey": "dwt62133-24",
    "outfitAbove": "red ruffle-collar cardigan",
    "outfitBelow": "patchwork wide-leg chambray pants",
    "autoPool": true
  },
  {
    "id": "low 31",
    "name": "Low 31",
    "poses": [
      {
        "id": "low 31",
        "label": "Low 31",
        "publicPath": "/models/low 31/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 31/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 31/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "vision",
    "expression": "teeth",
    "slug": "dwt62133-24-teeth",
    "poseKey": "dwt62133-24",
    "outfitAbove": "red ruffle-collar cardigan",
    "outfitBelow": "patchwork wide-leg chambray pants",
    "autoPool": true
  },
  {
    "id": "low 32",
    "name": "Low 32",
    "poses": [
      {
        "id": "low 32",
        "label": "Low 32",
        "publicPath": "/models/low 32/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 32/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 32/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, one arm raised to head, hand in pocket",
    "character": "vision",
    "expression": "neutral",
    "slug": "dwt62170-20-neutral",
    "poseKey": "dwt62170-20",
    "outfitAbove": "tan rodeo graphic sweater",
    "outfitBelow": "polka-dot barrel jeans",
    "autoPool": true
  },
  {
    "id": "low 33",
    "name": "Low 33",
    "poses": [
      {
        "id": "low 33",
        "label": "Low 33",
        "publicPath": "/models/low 33/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 33/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 33/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, one arm raised to head, hand in pocket",
    "character": "vision",
    "expression": "smile",
    "slug": "dwt62170-20-smile",
    "poseKey": "dwt62170-20",
    "outfitAbove": "tan rodeo graphic sweater",
    "outfitBelow": "polka-dot barrel jeans",
    "autoPool": true
  },
  {
    "id": "low 34",
    "name": "Low 34",
    "poses": [
      {
        "id": "low 34",
        "label": "Low 34",
        "publicPath": "/models/low 34/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 34/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 34/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, one arm raised to head, hand in pocket",
    "character": "vision",
    "expression": "teeth",
    "slug": "dwt62170-20-teeth",
    "poseKey": "dwt62170-20",
    "outfitAbove": "tan rodeo graphic sweater",
    "outfitBelow": "polka-dot barrel jeans",
    "autoPool": true
  },
  {
    "id": "low 35",
    "name": "Low 35",
    "poses": [
      {
        "id": "low 35",
        "label": "Low 35",
        "publicPath": "/models/low 35/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 35/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 35/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, hand in pocket",
    "character": "vision",
    "expression": "neutral",
    "slug": "dwt62170-21-neutral",
    "poseKey": "dwt62170-21",
    "outfitAbove": "tan rodeo graphic sweater",
    "outfitBelow": "polka-dot barrel jeans",
    "autoPool": true
  },
  {
    "id": "low 36",
    "name": "Low 36",
    "poses": [
      {
        "id": "low 36",
        "label": "Low 36",
        "publicPath": "/models/low 36/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 36/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 36/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, hand in pocket",
    "character": "vision",
    "expression": "smile",
    "slug": "dwt62170-21-smile",
    "poseKey": "dwt62170-21",
    "outfitAbove": "tan rodeo graphic sweater",
    "outfitBelow": "polka-dot barrel jeans",
    "autoPool": true
  },
  {
    "id": "low 37",
    "name": "Low 37",
    "poses": [
      {
        "id": "low 37",
        "label": "Low 37",
        "publicPath": "/models/low 37/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 37/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 37/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, hand in pocket",
    "character": "vision",
    "expression": "teeth",
    "slug": "dwt62170-21-teeth",
    "poseKey": "dwt62170-21",
    "outfitAbove": "tan rodeo graphic sweater",
    "outfitBelow": "polka-dot barrel jeans",
    "autoPool": true
  },
  {
    "id": "low 53",
    "name": "Low 53",
    "poses": [
      {
        "id": "low 53",
        "label": "Low 53",
        "publicPath": "/models/low 53/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 53/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 53/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "celine",
    "expression": "neutral",
    "slug": "dwt62133-24-celine-neutral",
    "poseKey": "dwt62133-24-celine",
    "autoPool": true
  },
  {
    "id": "low 54",
    "name": "Low 54",
    "poses": [
      {
        "id": "low 54",
        "label": "Low 54",
        "publicPath": "/models/low 54/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 54/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 54/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "celine",
    "expression": "smile",
    "slug": "dwt62133-24-celine-smile",
    "poseKey": "dwt62133-24-celine",
    "autoPool": true
  },
  {
    "id": "low 55",
    "name": "Low 55",
    "poses": [
      {
        "id": "low 55",
        "label": "Low 55",
        "publicPath": "/models/low 55/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 55/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 55/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "celine",
    "expression": "smirk",
    "slug": "dwt62133-24-celine-smirk",
    "poseKey": "dwt62133-24-celine",
    "autoPool": true
  },
  {
    "id": "low 56",
    "name": "Low 56",
    "poses": [
      {
        "id": "low 56",
        "label": "Low 56",
        "publicPath": "/models/low 56/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 56/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 56/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "celine",
    "expression": "teeth",
    "slug": "dwt62133-24-celine-teeth",
    "poseKey": "dwt62133-24-celine",
    "autoPool": true
  },
  {
    "id": "low 57",
    "name": "Low 57",
    "poses": [
      {
        "id": "low 57",
        "label": "Low 57",
        "publicPath": "/models/low 57/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 57/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 57/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, hand in pocket",
    "character": "celine",
    "expression": "neutral",
    "slug": "dwt62170-21-celine-neutral",
    "poseKey": "dwt62170-21-celine",
    "autoPool": true
  },
  {
    "id": "low 58",
    "name": "Low 58",
    "poses": [
      {
        "id": "low 58",
        "label": "Low 58",
        "publicPath": "/models/low 58/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 58/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 58/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, hand in pocket",
    "character": "celine",
    "expression": "smile",
    "slug": "dwt62170-21-celine-smile",
    "poseKey": "dwt62170-21-celine",
    "autoPool": true
  },
  {
    "id": "low 59",
    "name": "Low 59",
    "poses": [
      {
        "id": "low 59",
        "label": "Low 59",
        "publicPath": "/models/low 59/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 59/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 59/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, hand in pocket",
    "character": "celine",
    "expression": "smirk",
    "slug": "dwt62170-21-celine-smirk",
    "poseKey": "dwt62170-21-celine",
    "autoPool": true
  },
  {
    "id": "low 60",
    "name": "Low 60",
    "poses": [
      {
        "id": "low 60",
        "label": "Low 60",
        "publicPath": "/models/low 60/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/low 60/front.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/low 60/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, hand in pocket",
    "character": "celine",
    "expression": "teeth",
    "slug": "dwt62170-21-celine-teeth",
    "poseKey": "dwt62170-21-celine",
    "autoPool": true
  },
  {
    "id": "studio 03",
    "name": "Studio 03",
    "poses": [
      {
        "id": "studio 03",
        "label": "Studio 03",
        "publicPath": "/models/studio 03/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 03/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 03/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 03/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 03/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides, feet apart",
    "outfitAbove": "beige textured hooded button-up",
    "outfitBelow": "cream wide-leg trousers",
    "autoPool": true
  },
  {
    "id": "studio 04",
    "name": "Studio 04",
    "poses": [
      {
        "id": "studio 04",
        "label": "Studio 04",
        "publicPath": "/models/studio 04/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 04/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 04/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 04/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 04/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides, feet apart",
    "outfitAbove": "leopard print bomber jacket",
    "outfitBelow": "heather grey wide-leg sweatpants",
    "autoPool": true
  },
  {
    "id": "studio 05",
    "name": "Studio 05",
    "poses": [
      {
        "id": "studio 05",
        "label": "Studio 05",
        "publicPath": "/models/studio 05/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 05/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 05/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 05/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 05/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, both thumbs hooked in front pockets",
    "outfitAbove": "ivory ribbed turtleneck sweater",
    "outfitBelow": "brown plaid barrel trousers",
    "autoPool": true
  },
  {
    "id": "studio 06",
    "name": "Studio 06",
    "poses": [
      {
        "id": "studio 06",
        "label": "Studio 06",
        "publicPath": "/models/studio 06/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 06/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 06/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 06/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 06/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, one hand in pocket",
    "outfitAbove": "distressed cable-knit sweater",
    "outfitBelow": "acid-wash wide-leg jeans",
    "autoPool": true
  },
  {
    "id": "studio 07",
    "name": "Studio 07",
    "poses": [
      {
        "id": "studio 07",
        "label": "Studio 07",
        "publicPath": "/models/studio 07/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 07/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 07/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 07/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 07/side.jpg"
          }
        }
      }
    ],
    "wears": "shorts",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides, feet apart",
    "outfitAbove": "striped square-neck tank top",
    "outfitBelow": "multicolor striped linen shorts",
    "autoPool": true
  },
  {
    "id": "studio 09",
    "name": "Studio 09",
    "poses": [
      {
        "id": "studio 09",
        "label": "Studio 09",
        "publicPath": "/models/studio 09/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 09/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 09/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 09/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 09/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing upright, hands in pockets, feet slightly apart",
    "outfitAbove": "black unicorn-print cardigan",
    "outfitBelow": "polka-dot wide-leg trousers",
    "autoPool": true
  },
  {
    "id": "studio 10",
    "name": "Studio 10",
    "poses": [
      {
        "id": "studio 10",
        "label": "Studio 10",
        "publicPath": "/models/studio 10/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 10/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 10/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 10/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 10/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "outfitAbove": "taupe turtleneck sweater",
    "outfitBelow": "patchwork wide-leg jeans",
    "autoPool": true
  },
  {
    "id": "studio 19",
    "name": "Studio 19",
    "poses": [
      {
        "id": "studio 19",
        "label": "Studio 19",
        "publicPath": "/models/studio 19/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 19/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 19/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 19/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 19/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, right hand on hip, feet apart",
    "outfitAbove": "grey layered henley tank",
    "outfitBelow": "olive balloon barrel pants",
    "autoPool": true
  },
  {
    "id": "studio 20",
    "name": "Studio 20",
    "poses": [
      {
        "id": "studio 20",
        "label": "Studio 20",
        "publicPath": "/models/studio 20/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 20/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 20/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 20/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 20/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, arms relaxed",
    "outfitAbove": "black crewneck sweater layered tee",
    "outfitBelow": "charcoal pleated wide-leg trousers",
    "autoPool": true
  },
  {
    "id": "studio 22",
    "name": "Studio 22",
    "poses": [
      {
        "id": "studio 22",
        "label": "Studio 22",
        "publicPath": "/models/studio 22/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 22/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 22/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 22/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 22/side.jpg"
          }
        }
      }
    ],
    "wears": "skirt",
    "lowOk": false,
    "pose": "standing upright, arms at sides, feet slightly apart",
    "outfitAbove": "black sleeveless turtleneck top",
    "outfitBelow": "leopard print lace-hem midi skirt",
    "autoPool": true
  },
  {
    "id": "studio 25",
    "name": "Studio 25",
    "poses": [
      {
        "id": "studio 25",
        "label": "Studio 25",
        "publicPath": "/models/studio 25/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 25/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 25/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 25/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 25/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "Standing straight, one hand in pocket, feet apart",
    "outfitAbove": "taupe graphic tee",
    "outfitBelow": "brown polka-dot barrel pants",
    "autoPool": true
  },
  {
    "id": "studio 28",
    "name": "Studio 28",
    "poses": [
      {
        "id": "studio 28",
        "label": "Studio 28",
        "publicPath": "/models/studio 28/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 28/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 28/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 28/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 28/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "vision",
    "expression": "neutral",
    "slug": "dwt62133-24-neutral",
    "poseKey": "dwt62133-24",
    "outfitAbove": "red ruffle-collar cardigan",
    "outfitBelow": "patchwork wide-leg chambray pants",
    "autoPool": true
  },
  {
    "id": "studio 29",
    "name": "Studio 29",
    "poses": [
      {
        "id": "studio 29",
        "label": "Studio 29",
        "publicPath": "/models/studio 29/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 29/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 29/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 29/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 29/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "vision",
    "expression": "smile",
    "slug": "dwt62133-24-smile",
    "poseKey": "dwt62133-24",
    "outfitAbove": "red ruffle-collar cardigan",
    "outfitBelow": "patchwork wide-leg chambray pants",
    "autoPool": true
  },
  {
    "id": "studio 30",
    "name": "Studio 30",
    "poses": [
      {
        "id": "studio 30",
        "label": "Studio 30",
        "publicPath": "/models/studio 30/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 30/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 30/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 30/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 30/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "vision",
    "expression": "smirk",
    "slug": "dwt62133-24-smirk",
    "poseKey": "dwt62133-24",
    "outfitAbove": "red ruffle-collar cardigan",
    "outfitBelow": "patchwork wide-leg chambray pants",
    "autoPool": true
  },
  {
    "id": "studio 31",
    "name": "Studio 31",
    "poses": [
      {
        "id": "studio 31",
        "label": "Studio 31",
        "publicPath": "/models/studio 31/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 31/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 31/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 31/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 31/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "vision",
    "expression": "teeth",
    "slug": "dwt62133-24-teeth",
    "poseKey": "dwt62133-24",
    "outfitAbove": "red ruffle-collar cardigan",
    "outfitBelow": "patchwork wide-leg chambray pants",
    "autoPool": true
  },
  {
    "id": "studio 32",
    "name": "Studio 32",
    "poses": [
      {
        "id": "studio 32",
        "label": "Studio 32",
        "publicPath": "/models/studio 32/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 32/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 32/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 32/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 32/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, one arm raised to head, hand in pocket",
    "character": "vision",
    "expression": "neutral",
    "slug": "dwt62170-20-neutral",
    "poseKey": "dwt62170-20",
    "outfitAbove": "tan rodeo graphic sweater",
    "outfitBelow": "polka-dot barrel jeans",
    "autoPool": true
  },
  {
    "id": "studio 33",
    "name": "Studio 33",
    "poses": [
      {
        "id": "studio 33",
        "label": "Studio 33",
        "publicPath": "/models/studio 33/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 33/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 33/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 33/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 33/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, one arm raised to head, hand in pocket",
    "character": "vision",
    "expression": "smile",
    "slug": "dwt62170-20-smile",
    "poseKey": "dwt62170-20",
    "outfitAbove": "tan rodeo graphic sweater",
    "outfitBelow": "polka-dot barrel jeans",
    "autoPool": true
  },
  {
    "id": "studio 34",
    "name": "Studio 34",
    "poses": [
      {
        "id": "studio 34",
        "label": "Studio 34",
        "publicPath": "/models/studio 34/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 34/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 34/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 34/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 34/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, one arm raised to head, hand in pocket",
    "character": "vision",
    "expression": "teeth",
    "slug": "dwt62170-20-teeth",
    "poseKey": "dwt62170-20",
    "outfitAbove": "tan rodeo graphic sweater",
    "outfitBelow": "polka-dot barrel jeans",
    "autoPool": true
  },
  {
    "id": "studio 35",
    "name": "Studio 35",
    "poses": [
      {
        "id": "studio 35",
        "label": "Studio 35",
        "publicPath": "/models/studio 35/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 35/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 35/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 35/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 35/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, hand in pocket",
    "character": "vision",
    "expression": "neutral",
    "slug": "dwt62170-21-neutral",
    "poseKey": "dwt62170-21",
    "outfitAbove": "tan rodeo graphic sweater",
    "outfitBelow": "polka-dot barrel jeans",
    "autoPool": true
  },
  {
    "id": "studio 36",
    "name": "Studio 36",
    "poses": [
      {
        "id": "studio 36",
        "label": "Studio 36",
        "publicPath": "/models/studio 36/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 36/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 36/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 36/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 36/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, hand in pocket",
    "character": "vision",
    "expression": "smile",
    "slug": "dwt62170-21-smile",
    "poseKey": "dwt62170-21",
    "outfitAbove": "tan rodeo graphic sweater",
    "outfitBelow": "polka-dot barrel jeans",
    "autoPool": true
  },
  {
    "id": "studio 37",
    "name": "Studio 37",
    "poses": [
      {
        "id": "studio 37",
        "label": "Studio 37",
        "publicPath": "/models/studio 37/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 37/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 37/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 37/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 37/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, hand in pocket",
    "character": "vision",
    "expression": "teeth",
    "slug": "dwt62170-21-teeth",
    "poseKey": "dwt62170-21",
    "outfitAbove": "tan rodeo graphic sweater",
    "outfitBelow": "polka-dot barrel jeans",
    "autoPool": true
  },
  {
    "id": "studio 53",
    "name": "Studio 53",
    "poses": [
      {
        "id": "studio 53",
        "label": "Studio 53",
        "publicPath": "/models/studio 53/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 53/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 53/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 53/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 53/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "celine",
    "expression": "neutral",
    "slug": "dwt62133-24-celine-neutral",
    "poseKey": "dwt62133-24-celine",
    "autoPool": true
  },
  {
    "id": "studio 54",
    "name": "Studio 54",
    "poses": [
      {
        "id": "studio 54",
        "label": "Studio 54",
        "publicPath": "/models/studio 54/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 54/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 54/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 54/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 54/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "celine",
    "expression": "smile",
    "slug": "dwt62133-24-celine-smile",
    "poseKey": "dwt62133-24-celine",
    "autoPool": true
  },
  {
    "id": "studio 55",
    "name": "Studio 55",
    "poses": [
      {
        "id": "studio 55",
        "label": "Studio 55",
        "publicPath": "/models/studio 55/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 55/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 55/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 55/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 55/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "celine",
    "expression": "smirk",
    "slug": "dwt62133-24-celine-smirk",
    "poseKey": "dwt62133-24-celine",
    "autoPool": true
  },
  {
    "id": "studio 56",
    "name": "Studio 56",
    "poses": [
      {
        "id": "studio 56",
        "label": "Studio 56",
        "publicPath": "/models/studio 56/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 56/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 56/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 56/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 56/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing straight, arms relaxed at sides",
    "character": "celine",
    "expression": "teeth",
    "slug": "dwt62133-24-celine-teeth",
    "poseKey": "dwt62133-24-celine",
    "autoPool": true
  },
  {
    "id": "studio 57",
    "name": "Studio 57",
    "poses": [
      {
        "id": "studio 57",
        "label": "Studio 57",
        "publicPath": "/models/studio 57/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 57/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 57/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 57/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 57/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, hand in pocket",
    "character": "celine",
    "expression": "neutral",
    "slug": "dwt62170-21-celine-neutral",
    "poseKey": "dwt62170-21-celine",
    "autoPool": true
  },
  {
    "id": "studio 58",
    "name": "Studio 58",
    "poses": [
      {
        "id": "studio 58",
        "label": "Studio 58",
        "publicPath": "/models/studio 58/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 58/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 58/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 58/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 58/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, hand in pocket",
    "character": "celine",
    "expression": "smile",
    "slug": "dwt62170-21-celine-smile",
    "poseKey": "dwt62170-21-celine",
    "autoPool": true
  },
  {
    "id": "studio 59",
    "name": "Studio 59",
    "poses": [
      {
        "id": "studio 59",
        "label": "Studio 59",
        "publicPath": "/models/studio 59/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 59/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 59/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 59/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 59/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, hand in pocket",
    "character": "celine",
    "expression": "smirk",
    "slug": "dwt62170-21-celine-smirk",
    "poseKey": "dwt62170-21-celine",
    "autoPool": true
  },
  {
    "id": "studio 60",
    "name": "Studio 60",
    "poses": [
      {
        "id": "studio 60",
        "label": "Studio 60",
        "publicPath": "/models/studio 60/front.jpg",
        "filename": "front.jpg",
        "subdir": "",
        "views": {
          "back": {
            "filename": "back.jpg",
            "publicPath": "/models/studio 60/back.jpg"
          },
          "front": {
            "filename": "front.jpg",
            "publicPath": "/models/studio 60/front.jpg"
          },
          "full": {
            "filename": "full.jpg",
            "publicPath": "/models/studio 60/full.jpg"
          },
          "side": {
            "filename": "side.jpg",
            "publicPath": "/models/studio 60/side.jpg"
          }
        }
      }
    ],
    "wears": "pants",
    "lowOk": true,
    "pose": "standing, weight on one leg, hand in pocket",
    "character": "celine",
    "expression": "teeth",
    "slug": "dwt62170-21-celine-teeth",
    "poseKey": "dwt62170-21-celine",
    "autoPool": true
  }
] as unknown as HumanModel[];
