import {beforeEach,describe,expect,it,vi} from 'vitest';
import {IDENTITY_MASTERS,IDENTITY_PROMPT,IDENTITY_VIEWS,identityGenerationParams,identityTaskId,validIdentitySetId,type IdentitySet} from './reference-identity-core';
import {applyCatalogChanges} from './model-admin-core';
vi.mock('./fal',()=>({generate:vi.fn()}));
vi.mock('./shot-tasks',()=>({writeShotTask:vi.fn()}));
vi.mock('@vercel/blob',()=>({put:vi.fn()}));
vi.mock('sharp',()=>({default:vi.fn(()=>({metadata:async()=>({format:'png'})}))}));
import {generate} from './fal';
import {writeShotTask} from './shot-tasks';
import {put} from '@vercel/blob';
import {renderIdentityView} from './reference-identity';
const id='11111111-1111-4111-a111-111111111111';
const set:IdentitySet={id,name:'Test',createdAt:'2026-09-10',identity:{...IDENTITY_MASTERS[0],filename:'celine.png'},inputs:{front:{url:'https://source/front.jpg',filename:'front.jpg'},side:{url:'https://source/side.jpg',filename:'side.jpg'}},prompt:IDENTITY_PROMPT,modelId:'gpt-image-25'};
beforeEach(()=>{vi.clearAllMocks();vi.stubEnv('BLOB_READ_WRITE_TOKEN','test');vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,arrayBuffer:async()=>new Uint8Array([1,2,3]).buffer}));vi.mocked(generate).mockResolvedValue({modelId:'gpt-image-25',images:[{url:'https://provider/result.png'}],requestId:'provider-id'});vi.mocked(put).mockResolvedValue({url:'https://own-store/result.png'} as any);});
describe('independent identity edits',()=>{
 it('uses identical prompts and original matching angles without rewrite, mask, resizing or generated-front chaining',()=>{
  for(const view of IDENTITY_VIEWS){const p=identityGenerationParams(`original-${view}`,'original-master');expect(p.imageUrls).toEqual([`original-${view}`,'original-master']);expect(p.prompt).toBe(IDENTITY_PROMPT);expect(p.verbatimPrompt).toBe(true);expect(p.raw).toBeUndefined();expect(p.maskUrl).toBeUndefined();expect(p.useDefaultReference).toBe(false);expect(p.outputSize).toBeNull();expect(p.numImages).toBe(1);}
 });
 it('validates IDs before paths are constructed',()=>{expect(validIdentitySetId(id)).toBe(true);expect(validIdentitySetId('../x')).toBe(false);expect(validIdentitySetId(null)).toBe(false);expect(identityTaskId(id,'front').length).toBeLessThan(65);});
 it('stores the original generated bytes and provenance',async()=>{
  await renderIdentityView(set,'side',{id:identityTaskId(id,'side'),view:'side',status:'running',createdAt:1,updatedAt:1});
  expect(generate).toHaveBeenCalledWith(identityGenerationParams('https://source/side.jpg',set.identity.url));
  expect(put).toHaveBeenCalledWith(expect.stringMatching(/^model-admin\/photos\/.*\.png$/),Buffer.from([1,2,3]),expect.any(Object));
  expect(writeShotTask).toHaveBeenCalledWith(expect.objectContaining({status:'done',result:expect.objectContaining({imageUrl:'https://own-store/result.png',requestId:'provider-id'})}));
 });
 it('keeps a downloadable provider result when permanent storage fails without generating twice',async()=>{
  vi.mocked(put).mockRejectedValue(Error('storage offline'));
  await renderIdentityView(set,'front',{id,view:'front',status:'running',createdAt:1,updatedAt:1});
  expect(generate).toHaveBeenCalledTimes(1);expect(put).toHaveBeenCalledTimes(3);
  expect(writeShotTask).toHaveBeenCalledWith(expect.objectContaining({status:'done',result:expect.objectContaining({imageUrl:'https://provider/result.png',persistenceWarning:expect.any(String)})}));
 });
 it('records a generation failure per view',async()=>{
  vi.mocked(generate).mockRejectedValue(Error('provider failure'));
  await renderIdentityView(set,'front',{id,view:'front',status:'running',createdAt:1,updatedAt:1});
  expect(writeShotTask).toHaveBeenCalledWith(expect.objectContaining({status:'failed',result:expect.objectContaining({error:'provider failure'})}));
 });
 it('does not call the provider for missing views',async()=>{
  await renderIdentityView(set,'back',{id,view:'back',status:'running',createdAt:1,updatedAt:1});expect(generate).not.toHaveBeenCalled();
 });
 it('handles empty provider output',async()=>{
  vi.mocked(generate).mockResolvedValue({modelId:'gpt-image-25',images:[]});await renderIdentityView(set,'front',{id,view:'front',status:'running',createdAt:1,updatedAt:1});expect(writeShotTask).toHaveBeenCalledWith(expect.objectContaining({status:'failed'}));
 });
 it('imports the complete selected reference set atomically and preserves later photo replacements on duplicate import',()=>{
  const create:any={id:'a',at:'1',kind:'model',modelId:id,create:true,patch:{name:'Celine test',character:'Celine'},referenceSet:{poseId:'p',label:'Test',photos:{front:{filename:'front.png',publicPath:'/front.png'},side:{filename:'side.png',publicPath:'/side.png'}}}};
  const models=applyCatalogChanges([], [create,{id:'b',at:'2',kind:'photo',modelId:id,poseId:'p',view:'front',photo:{filename:'new.png',publicPath:'/new.png'}},{...create,id:'c',at:'3'}]);
  expect(models).toHaveLength(1);expect(models[0].poses).toHaveLength(1);expect(models[0].poses[0].views.front?.publicPath).toBe('/new.png');expect(models[0].poses[0].views.side?.publicPath).toBe('/side.png');expect(models[0].poses[0].views.back).toBeUndefined();
 });
});
