/**
 * Regenerate lib/models-static-manifest.ts from public/models.
 *
 * next.config.js excludes public/models from the API functions' file tracing,
 * so on Vercel the routes cannot read the plate folders — they fall back to a
 * static manifest. That manifest was written once by hand, which meant twelve
 * new plate sets landed on disk, deployed as static files, and stayed
 * invisible to /api/model-shots: the catalogue it serves is this file.
 *
 * So it is generated now, from the same scan the local filesystem path uses,
 * and regenerating it is part of installing a plate.
 *
 *     npm run models:manifest
 */
import fs from "fs";
import path from "path";
import { listHumanModels } from "../lib/models-registry";

const models = listHumanModels();
if (!models.length) {
  console.error("no models found under public/models — refusing to write an empty manifest");
  process.exit(1);
}

const file = `// GENERATED by scripts/build-models-manifest.mts — do not edit by hand.
//
// next.config.js excludes public/models from the API functions' file tracing,
// so on Vercel the routes read this manifest instead of the filesystem. A plate
// that is on disk but missing here does not exist as far as the deployed API is
// concerned. Regenerate with: npm run models:manifest
import type { HumanModel } from "./models-registry";

export const STATIC_HUMAN_MODELS = ${JSON.stringify(models, null, 2)} as unknown as HumanModel[];
`;

const out = path.join(process.cwd(), "lib", "models-static-manifest.ts");
fs.writeFileSync(out, file);
console.log(`wrote ${models.length} models (${models.reduce((n, m) => n + m.poses.length, 0)} poses) -> ${out}`);
for (const m of models) console.log(`  ${m.id}: ${m.poses.length} pose(s)`);
